[project]
name = "mcp-research-server"
version = "0.1.0"
description = "MCP Research Server with arXiv integration"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic",
    "arxiv>=2.2.0",
    "mcp>=1.9.1",
    "nest-asyncio>=1.6.0",
    "python-dotenv>=1.1.0",
]
